import {DEFAULTS,compareSupply} from './medicineSupplyModel.mjs';
export const SUPPLY_TEXT = {
  fr:{title:'Combien de temps le stock tient-il ?',intro:'Laboratoire pédagogique : mêmes stocks, même incident, avec ou sans production de secours. Toutes les quantités sont fictives.',fields:['Demande quotidienne (unités)','Stock initial (jours de demande)','Durée de l’incident (jours)','Livraisons perdues (% de la demande)','Secours (% de la demande)','Jours entiers avant arrivée du secours'],run:'Recalculer',reset:'Réinitialiser',csv:'Exporter les calculs CSV',base:'Stock seul',backup:'Stock + secours',first:'Premier jour partiellement non couvert',unmet:'Demande non satisfaite',rate:'Part de la demande livrée',none:'Aucun sur la période',day:'Jour',units:'unités',details:'Détail jour par jour',stock:'Stock restant',demand:'Demande',delivered:'Livré',missing:'Non livré',method:'Le flux ordinaire restant arrive chaque jour. Le stock complète les livraisons. Un délai de 14 jours signifie un secours à partir du jour 15. Le secours est plafonné au flux perdu et ne reconstitue pas le stock. Les quantités manquantes ne sont pas rattrapées.',limit:'Aucune prévision de pénurie, aucune dose médicale, aucune recommandation de stock personnel. Pas de péremption, de hausse de demande ou de panne commune simulée.',chartTitle:'Stock de produits finis pendant l’incident',chartDesc:'Deux trajectoires de stock : sans secours et avec secours. Les valeurs exactes figurent dans le tableau.',source:'Source : calculs l0g, hypothèses fictives ; unité : produit fini abstrait ; horizon : durée saisie.',invalid:'Saisissez des nombres entiers dans les limites indiquées.',enabled:'Le stock de départ et le secours sont supposés immédiatement utilisables à leur date de disponibilité.',zeros:'Le secours vaut au maximum les livraisons perdues ; aucun surplus de production n’est simulé.'},
  en:{title:'How long does the inventory last?',intro:'Teaching lab: the same inventory and disruption, with or without backup production. All quantities are fictional.',fields:['Daily demand (units)','Initial inventory (days of demand)','Interruption duration (days)','Lost deliveries (% of demand)','Backup supply (% of demand)','Full days before backup arrives'],run:'Recalculate',reset:'Reset',csv:'Export calculations as CSV',base:'Inventory only',backup:'Inventory + backup',first:'First partially unserved day',unmet:'Unmet demand',rate:'Share of demand delivered',none:'None during this period',day:'Day',units:'units',details:'Day-by-day calculation',stock:'Inventory remaining',demand:'Demand',delivered:'Delivered',missing:'Unmet',method:'The remaining regular flow arrives daily. Inventory fills the delivery gap. A 14-day delay means backup starts on day 15. Backup is capped at lost deliveries and does not rebuild inventory. Unmet demand is not made up later.',limit:'Not a shortage forecast, a medical dose calculation or a personal stock recommendation. Expiry, rising demand and shared failures are not simulated.',chartTitle:'Finished-product inventory during the interruption',chartDesc:'Two inventory paths: without backup and with backup. Exact values are in the table.',source:'Source: l0g calculations, fictional assumptions; unit: abstract finished product; horizon: entered duration.',invalid:'Enter whole numbers within the stated limits.',enabled:'Initial inventory and backup output are assumed usable as soon as they are available.',zeros:'Backup cannot exceed lost deliveries; no surplus production is simulated.'}
};
export const esc = value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function supplyFmt(lang,number,digits=0){return new Intl.NumberFormat(lang==='fr'?'fr-FR':'en-GB',{maximumFractionDigits:digits}).format(number);}
export function supplyPlot(lang,comparison,mobile=false) {
  const {baseline:a,backup:b}=comparison;
  const w=mobile?400:640,h=mobile?350:340,l=mobile?88:100,r=28,top=50,bottom=62;
  const max=Math.max(1,a.initialStock),n=a.inputs.outageDays;
  const axisFormat=v=>v>=10000?new Intl.NumberFormat(lang==='fr'?'fr-FR':'en-GB',{notation:'compact',maximumFractionDigits:1}).format(v):supplyFmt(lang,v,1);
  const x=day=>l+day/n*(w-l-r),y=stock=>top+(1-stock/max)*(h-top-bottom);
  const points=q=>[[0,q.initialStock],...q.rows.map(v=>[v.day,v.endingStock])].map(([d,s])=>`${x(d).toFixed(3)},${y(s).toFixed(3)}`).join(' ');
  return {w,h,l,r,top,bottom,a:points(a),b:points(b),
    ticks:[0,.25,.5,.75,1].map(f=>({y:y(f*max),label:axisFormat(f*max)})),
    days:[...new Set(mobile?[0,Math.round(n/2),n]:[0,Math.round(n/4),Math.round(n/2),Math.round(3*n/4),n])].map(day=>({x:x(day),day}))};
}
export function renderSupplyChart(lang,comparison,id='medicine-stock-chart',mobile=false) {
  lang=lang==='en'?'en':'fr';
  if (!/^[a-zA-Z][a-zA-Z0-9-]*$/.test(id)) throw new RangeError('Invalid chart ID.');
  const t=SUPPLY_TEXT[lang],plot=supplyPlot(lang,comparison,mobile);
  const {w,h,l,r,bottom}=plot;
  const grid=plot.ticks.map((tick,i)=>`<line x1="${l}" x2="${w-r}" y1="${tick.y}" y2="${tick.y}" stroke="#34414b"/><text data-y-tick="${i}" x="${l-10}" y="${tick.y+5}" text-anchor="end" fill="#bacbd6" font-size="18">${esc(tick.label)}</text>`).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" style="width:100%;height:auto" data-supply-chart="${mobile?'small':'wide'}" role="img" aria-labelledby="${id}-t ${id}-d"><title id="${id}-t">${esc(t.chartTitle)}</title><desc id="${id}-d">${esc(t.chartDesc)}</desc><rect width="${w}" height="${h}" rx="12" fill="#0b0d10"/><g font-family="system-ui, sans-serif"><text x="${mobile?16:l}" y="26" font-size="${mobile?17:18}" fill="#e4f0f6">${esc(t.stock)} (${esc(t.units)})</text>${grid}<g data-x-ticks="">${plot.days.map(d=>`<text x="${d.x}" y="${h-bottom+26}" text-anchor="middle" fill="#bacbd6" font-size="${mobile?18:18}">${d.day}</text>`).join('')}</g><polyline data-series="a" points="${plot.a}" fill="none" stroke="#f6bd68" stroke-width="4" stroke-dasharray="9 6"/><polyline data-series="b" points="${plot.b}" fill="none" stroke="#50ddc0" stroke-width="3.5"/><text x="${w/2}" y="${h-12}" text-anchor="middle" fill="#bacbd6" font-size="18">${esc(t.day)}</text></g></svg>`;
}
export function renderSupplyResults(lang,comparison,id='medicine-result') {
  lang=lang==='en'?'en':'fr'; const t=SUPPLY_TEXT[lang];
  const card=(key,q)=>`<section class="ms-card ms-${key}"><h4>${esc(key==='base'?t.base:t.backup)}</h4><dl><div><dt>${esc(t.first)}</dt><dd data-metric="first-${key}">${q.firstShortage===null?esc(t.none):`${esc(t.day)} ${q.firstShortage}`}</dd></div><div><dt>${esc(t.unmet)}</dt><dd data-metric="unmet-${key}">${esc(supplyFmt(lang,q.totalUnmet,1))} <small>${esc(t.units)}</small></dd></div><div><dt>${esc(t.rate)}</dt><dd data-metric="rate-${key}">${esc(supplyFmt(lang,q.serviceRate*100,1))} %</dd></div></dl></section>`;
  return `<div class="ms-cards">${card('base',comparison.baseline)}${card('backup',comparison.backup)}</div><div class="ms-legend"><span class="ms-key-base">${esc(t.base)}</span><span class="ms-key-backup">${esc(t.backup)}</span></div><div class="ms-chart ms-chart-wide">${renderSupplyChart(lang,comparison,id+'-wide')}</div><div class="ms-chart ms-chart-small">${renderSupplyChart(lang,comparison,id+'-small',true)}</div><p class="ms-note">${esc(t.source)}</p>`;
}
export function renderSupplyRows(lang,comparison){
 lang=lang==='en'?'en':'fr'; const t=SUPPLY_TEXT[lang];
 return `<details class="ms-details"><summary>${esc(t.details)}</summary><div class="ms-table-scroll" tabindex="0" role="region" aria-label="${esc(t.details)}"><table><caption>${esc(t.details)} · ${esc(t.units)}</caption><thead><tr><th rowspan="2">${esc(t.day)}</th><th rowspan="2">${esc(t.demand)}</th><th colspan="2">${esc(t.base)}</th><th colspan="2">${esc(t.backup)}</th></tr><tr><th>${esc(t.stock)}</th><th>${esc(t.missing)}</th><th>${esc(t.stock)}</th><th>${esc(t.missing)}</th></tr></thead><tbody>${comparison.baseline.rows.map((a,i)=>{const b=comparison.backup.rows[i];return `<tr>${[a.day,a.demand,a.endingStock,a.unmet,b.endingStock,b.unmet].map(v=>`<td>${esc(supplyFmt(lang,v,1))}</td>`).join('')}</tr>`;}).join('')}</tbody></table></div></details>`;
}
export function renderMedicineSupplyLab(lang='fr') {
 lang=lang==='en'?'en':'fr'; const t=SUPPLY_TEXT[lang],id=`medicine-lab-${lang}`;
 const fields=[['dailyDemand',1,1000000000],['stockDays',0,365],['outageDays',1,365],['lostShare',0,100],['backupShare',0,100],['backupDelayDays',0,365]];
 const comparison=compareSupply(DEFAULTS);
 return `<section class="ms-lab" data-medicine-lab data-lang="${lang}" aria-labelledby="${id}-title"><div class="ms-lab-head"><p class="ms-eyebrow">l0g / ${lang==='fr'?'SIMULATION FICTIVE':'FICTIONAL SIMULATION'}</p><h3 id="${id}-title">${esc(t.title)}</h3><p>${esc(t.intro)}</p></div><fieldset class="ms-form" disabled><div class="ms-inputs">${fields.map(([key,min,max],i)=>`<label for="${id}-${key}">${esc(t.fields[i])}<input id="${id}-${key}" name="${key}" type="number" min="${min}" max="${max}" step="1" value="${DEFAULTS[key]}" inputmode="numeric" required /></label>`).join('')}</div><div class="ms-buttons"><button type="button" data-apply>${esc(t.run)}</button><button type="button" data-reset class="ms-secondary">${esc(t.reset)}</button><button type="button" data-export class="ms-secondary">${esc(t.csv)}</button></div><p class="ms-error" role="alert" hidden></p></fieldset><p class="ms-note">${esc(t.enabled)}</p><div data-results aria-live="polite" aria-atomic="true">${renderSupplyResults(lang,comparison,id+'-chart')}</div><p class="ms-note">${esc(t.method)}</p><div data-rows>${renderSupplyRows(lang,comparison)}</div><p class="ms-limit">${esc(t.limit)}</p><noscript><p>${lang==='fr'?'JavaScript désactivé : les résultats affichés correspondent au scénario initial ; le tableau reste accessible.':'JavaScript is disabled: displayed results use the initial scenario; the table remains available.'}</p></noscript></section>`;
}
