export const atlases = [
  {
    id: 'financement-ia',
    href: '/atlas/financement-ia/',
    label: 'Financement de l’IA',
    theme: 'ia',
    image: '/illustrations/news/openai-credit-guarantee-v1.jpg',
    eyebrow: 'Infrastructures · Capital · Garanties',
    description: 'Derrière les centres de données, des investisseurs, des locataires et des garants. Explorez les contrats qui les relient et les conditions de leurs engagements.',
    actors: 'Nvidia · OpenAI · SB Energy · AIP',
    question: 'Qui finance les infrastructures de l’IA ?',
  },
  {
    id: 'credit-prive',
    href: '/atlas/credit-prive/',
    label: 'Crédit privé',
    theme: 'credit',
    image: '/illustrations/news/credit-prive-logiciels-ia-v1.jpg',
    eyebrow: 'Fonds · Assureurs · Banques',
    description: 'Des capitaux des investisseurs aux entreprises financées, suivez le rôle des gérants, des assureurs et des banques dans les circuits du crédit privé.',
    actors: 'Apollo · Athene · Ares Capital · BNP Paribas',
    question: 'Par où passe l’argent avant d’être prêté ?',
  },
  {
    id: 'financement-petrole',
    href: '/atlas/petrole/',
    label: 'Financement du pétrole',
    theme: 'petrole',
    image: '/illustrations/news/oil-trade-bank-finance-v1.jpg',
    eyebrow: 'Cargaisons · Négoce · Recettes publiques',
    description: 'Du paiement d’une cargaison aux recettes d’un pays producteur, explorez les relations entre banques, négociants et emprunteurs.',
    actors: 'UniCredit · Trafigura · Glencore · Tchad',
    question: 'Qui avance l’argent, qui reçoit les recettes ?',
  },
] as const;
